s= set()
n1 = int(input("Enter number 1: "))
s.add(n1)
n1 = int(input("Enter number 2: "))
s.add(n1)
n1 = int(input("Enter number 3: "))
s.add(n1)
n1 = int(input("Enter number 4: "))
s.add(n1)
n1 = int(input("Enter number 5: "))
s.add(n1)
n1 = int(input("Enter number 6: "))
s.add(n1)
n1 = int(input("Enter number 7: "))
s.add(n1)
n1 = int(input("Enter number 8: "))
s.add(n1)

print(s)